apiVersion: v1
kind: Pod
metadata:
  name: lab53-podsecrets
spec:
  containers:
    - name: secretsdemo
      image: alpine
      command: ["sleep", "3600"]
      env:
        - name: LOGGING_LEVEL
          valueFrom:
            configMapKeyRef:
              name: lab52-configmap-demo          # Name of the Config Map.
              key: log_level                      # Name of the The key to fetch.
        - name: APPLICATION_NAME
          valueFrom:
            configMapKeyRef:
              name: lab52-configmap-demo
              key: app.name
        - name: AUTH_USER
          valueFrom:
            secretKeyRef:
              name: lab53-cred
              key: lab53username
        - name: AUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: lab53-cred
              key: lab53password                     
      volumeMounts:
      - name: config
        mountPath: "/config"
        readOnly: true
      - name: secret-keys
        mountPath: "/etc/secretkeys"
        readOnly: true        
  volumes:
  - name: config
    configMap:
      name: lab52-configmap-demo
      items:
      - key: "config.properties"
        path: "config.properties"
      - key: "config.json"
        path: "config.json"
  - name: secret-keys
    secret:
      secretName: lab53-keys
      items:
      - key: "lab52public.key"
        path: "private.key"
      - key: "lab52public.key"
        path: "public.key"        