apiVersion: v1
kind: Pod
metadata:
  name: lab52-pod
spec:
  containers:
    - name: confmapdemo
      image: alpine
      command: ["sleep", "3600"]
      env:
        - name: LOGGING_LEVEL
          valueFrom:
            configMapKeyRef:
              name: lab52-configmap-demo          # Name of the Config Map.
              key: log_level                      # Name of the The key to fetch.
        - name: APPLICATION_NAME
          valueFrom:
            configMapKeyRef:
              name: lab52-configmap-demo
              key: app.name
      volumeMounts:
      - name: config
        mountPath: "/config"
        readOnly: true
  volumes:
  - name: config
    configMap:
      name: lab52-configmap-demo
      items:
      - key: "config.properties"
        path: "config.properties"
      - key: "config.json"
        path: "config.json"