#Taken from https://raw.githubusercontent.com/kubernetes/website/main/content/en/examples/pods/simple-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx-simple
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
