kind: Pod
apiVersion: v1
metadata:
  name: lab43
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
          name: "http"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: my-custom-storage
  volumes:
    - name: my-custom-storage
      persistentVolumeClaim:
       claimName: my-custom-pvc