#Taken from https://raw.githubusercontent.com/kubernetes/website/main/content/en/examples/pods/simple-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-nginx
spec:
  containers:
  - name: lab54
    image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
    ports:
    - containerPort: 80
