apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysite2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.24-alpine-slim
        ports:
        - containerPort: 80
          name: http